import re

from corpus_keys import Gold, leaf_of


# a set generated for this comparison is generated by these two: exported, not private
def clean_gold(text):
    return re.sub(r"[_*`]", "", text or "").strip().lower()


# a section path names its section by the leaf alone, its number and emphasis read away
def heading_text(section):
    leaf = leaf_of(section)
    return clean_gold(re.sub(r"^\d+\.\s*", "", leaf))


# an older mark is a path fragment and matches by containment, an exact gold by its file: hit@k stands on this
def rank_of_gold(sources, gold) -> int | None:
    gold = Gold.coerce(gold)
    return next((i for i, s in enumerate(sources, 1) if gold.holds_file(s)), None)


# an older gold names its file and leaves the heading to its text
def rank_of_section(sections, gold, gold_heading):
    gold, heading_wanted = Gold.coerce(gold), clean_gold(gold_heading)
    for i, (source, heading) in enumerate(sections, 1):
        if gold.holds_file(source) and heading and heading == heading_wanted:
            return i
    return None


# the pair the standard takes as an id, collapsed as `ranked_lists` does: one metric, one spelling
def section_ids(chunks) -> list[tuple[str, str | None]]:
    out = []
    for c in chunks or []:
        if not c:
            continue
        key = (c["source"], heading_text(c.get("section")))
        if key not in out:
            out.append(key)
    return out


# the gold section by its own rank, so a chunk of the right file in the wrong section is not a hit
def rank_of_gold_section(chunks, gold, gold_heading=None) -> int | None:
    gold = Gold.coerce(gold)
    if not gold.exact:
        return rank_of_section(section_ids(chunks), gold, gold_heading)
    return rank_of_exact_section([c for c in (chunks or []) if c], gold)


# an exact gold ranks the distinct sections by their whole path, a sub-section of the gold counting as it
def rank_of_exact_section(chunks, gold: Gold) -> int | None:
    seen = []
    for c in chunks:
        key = (c["source"], c.get("section"))
        if key in seen:
            continue
        seen.append(key)
        if gold.holds_section(key[0], key[1], c.get("versions")):
            return len(seen)
    return None


# how many golds a set of files holds, by the one file rule
def count_marking(files: list[str], golds) -> int:
    return sum(1 for gold in golds if any(Gold.coerce(gold).holds_file(f) for f in files))
