import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

OUT = ROOT / "docs" / "diagrams" / "agent_graph.puml"
LABELS = {
    "model": ["call the LLM with the tools this hop is allowed"],
    "retrieve": ["our dispatch, raw results into the state,", "no message for the model"],
    "grade": ["the grader reads each chunk and drops", "what it calls foreign; off, a pass-through"],
    "fallback": ["the coverage verdict fired: drop weak,", "announce, open external"],
    "emit": ["tool messages for the model, after the verdict"],
    "final": ["last turn without tools,", "agent.no_evidence when nothing answered"],
}


def _end(node: str) -> str:
    return "[*]" if node in ("__start__", "__end__") else node


def render() -> str:
    from orchestrators.graph import build

    graph = build().get_graph()
    lines = [
        "@startuml agent_graph",
        "' generated by scripts/graph_to_puml.py from the compiled graph, do not edit by hand",
        "hide empty description",
        "",
    ]
    for node in graph.nodes:
        if node.startswith("__"):
            continue
        lines += [f"state {node}"] + [f"{node} : {line}" for line in LABELS.get(node, [])]
    lines.append("")
    for edge in graph.edges:
        arrow = "-[dashed]->" if edge.conditional else "-->"
        label = f" : {edge.data}" if getattr(edge, "data", None) else ""
        lines.append(f"{_end(edge.source)} {arrow} {_end(edge.target)}{label}")
    lines.append("@enduml")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    drawn = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != drawn:
            print(f"{OUT} is out of date, run scripts/graph_to_puml.py")
            raise SystemExit(1)
        print(f"{OUT} matches the compiled graph")
    else:
        OUT.write_text(drawn)
        print(f"wrote {OUT}")
