import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "app"))

OUT = ROOT / "docs" / "diagrams" / "agent_graph.d2"
LABELS = {
    "model": "model\\ncall the LLM with the tools this hop is allowed",
    "tools": "tools\\nour dispatch, then one coverage verdict for the turn",
    "final": "final\\nlast turn without tools, agent.no_evidence when nothing answered",
    "__start__": "start",
    "__end__": "end",
}


def render() -> str:
    from orchestrators.graph import build

    graph = build().get_graph()
    lines = [
        "# generated by scripts/graph_to_d2.py from the compiled graph, do not edit by hand",
        "direction: down",
        "",
    ]
    for node in graph.nodes:
        lines.append(f'{node}: "{LABELS.get(node, node)}"')
    lines.append("")
    for edge in graph.edges:
        style = " {style.stroke-dash: 3}" if edge.conditional else ""
        label = f": {edge.data}" if getattr(edge, "data", None) else ""
        lines.append(f"{edge.source} -> {edge.target}{label}{style}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    drawn = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != drawn:
            print(f"{OUT} is out of date, run scripts/graph_to_d2.py")
            raise SystemExit(1)
        print(f"{OUT} matches the compiled graph")
    else:
        OUT.write_text(drawn)
        print(f"wrote {OUT}")
